#!/bin/bash
#
# chkconfig: 2345 85 15
# description: Starts and stops the PostgreSQL 9.2 database server

# Source function library.
if [ -f /etc/rc.d/functions ];
then
    . /etc/init.d/functions
fi

# PostgreSQL Service script for Linux

start()
{
	echo $"Starting PostgreSQL 9.2: "
	su - <%= @owner %> -c "LD_LIBRARY_PATH=<%= @postgres_dir %>/bin/lib <%= @postgres_dir %>/bin/pg_ctl -w start -D \"<%= @postgres_dir %>/data/\" -l \"<%= @postgres_dir %>/data/pg_log/startup.log\""
	
	if [ -e "<%= @postgres_dir %>/data/postmaster.pid" ]
	then
		echo "PostgreSQL 9.2 started successfully"
                exit 0
	else
		echo "PostgreSQL 9.2 did not start in a timely fashion, please see <%= @postgres_dir %>/data/pg_log/startup.log for details"
                exit 1
	fi
}

stop()
{
	echo $"Stopping PostgreSQL 9.2: "
	su - <%= @owner %> -c "LD_LIBRARY_PATH=<%= @postgres_dir %>/bin/lib <%= @postgres_dir %>/bin/pg_ctl stop -m fast -w -D \"<%= @postgres_dir %>/data/\""
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        sleep 3
        start
        ;;
  condrestart)
        if [ -f "<%= @postgres_dir %>/data/postmaster.pid" ]; then
            stop
            sleep 3
            start
        fi
        ;;
  status)
        su - <%= @owner %> -c "LD_LIBRARY_PATH=<%= @postgres_dir %>/bin/lib <%= @postgres_dir %>/bin/pg_ctl status -D \"<%= @postgres_dir %>/data/\""
        ;;
  *)
        echo $"Usage: /etc/init.d/postgresql {start|stop|restart|condrestart|status}"
        exit 1
esac

