#!/bin/sh
#
# IScopeWV <summary>
#
# chkconfig:   2345 20 80
# description: "Starts and stops the CA APM Introscope WebView"
#

# Source function library.
. /etc/rc.d/init.d/functions

export WILYHOME=<%= scope.lookupvar("caapm::em::user_install_dir") %>
export WILYPARENT=${WILYHOME}

cd ${WILYHOME}/bin

./WVCtrl.sh $*

